### ISSUE TITLE
JSON Connect Connector Issue

### ISSUE THREAD

**Issue by polluct** [googledatastudio/community-connectors#217] opened 2019-07-15 12:09 UTC
google login temporarily deactivated/not possible

**Comment by Divan369** [comment] 2019-07-16 10:35
I am also having the same issue, is there a way to bypass this while we wait for google to verify this open-source connector?

**Comment by caiolocalsearch** [comment] 2019-07-16 12:10
Same here!

**Comment by romaniv1024** [comment] 2019-07-17 13:33
Duplicate of #214

**Comment by diminishedprime** [comment] 2019-07-25 17:31
This deployment for JSON connect is no longer supported. If you would like to use this connector, please deploy it yourself using [these instructions].

[these instructions]: https://github.com/googledatastudio/community-connectors/tree/master/JSON-connect#set-up-the-community-connector-for-personal-use

**Closed by diminishedprime** 2019-07-25 17:31 UTC
