### ISSUE TITLE
Firestore Connector Issue

### ISSUE THREAD

**Issue by esdrasdemorais** [googledatastudio/community-connectors#250] opened 2019-08-03 20:01 UTC
FireStore Community Connector From https://github.com/googledatastudio/community-connectors/tree/master/firestore Doesn't Work.

Help me Please.

**Comment by esdrasdemorais** [comment] 2019-08-03 20:19
TypeError: Cannot find function getAuthToken in object [object Object]. (line 47, file "Firestore")

**Comment by diminishedprime** [comment] 2019-08-14 18:06
Duplicate of #251

**Closed by diminishedprime** 2019-08-14 18:06 UTC

**Comment by fye-campbell** [comment] 2019-08-16 13:33
Did you make any progress with this?  I think I'm having the same issue.
