### ISSUE TITLE
Column name and data does no correspond

### ISSUE THREAD

**Issue by miguelangelmestres** [googledatastudio/community-connectors#253] opened 2019-08-06 09:02 UTC
**Which connector were you using?**
fetch-csv

**What's going wrong with this connector?**
When exploring data,  column name and data does no correspond
For example:
A column containing: Day of week displays the year 

Everything worked fine since last 02/08/2019. May be Google Data Studio update broke the connector

Some screenshots atatched
![Figure 2](https://user-images.githubusercontent.com/33750346/62526374-6ba2f880-b839-11e9-9b6b-66159b587ab4.png)
![Figure 1](https://user-images.githubusercontent.com/33750346/62526375-6c3b8f00-b839-11e9-866a-b71a416fab6b.png)

**Comment by esdrasdemorais** [comment] 2019-08-07 02:09
Please, how could you connect? Because my deploy sent this message:

Community Connector Error

There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.
Connector details

There was an error caused by this connector.

TypeError: Cannot find function getAuthToken in object [object Object]. (line 47, file "Firestore")

**Comment by piotrek94** [comment] 2019-08-07 09:48
Hey @miguelangelmestres ,
I experienced the same problem as you. I found where the problem is and I wrote a patch ([MR](https://github.com/googledatastudio/community-connectors/pull/255)). The problem is caused by the order in `schema` in `Response` object for method `getData()`.

Also, I noticed that `fetch-csv connector` disappeared from the list of possible connectors to choose when I am creating new Data Source. And I am wondering why.


![fetch](https://user-images.githubusercontent.com/9871431/62613087-0f0f0e80-b909-11e9-835f-216338578cd8.jpg)

**Comment by miguelangelmestres** [comment] 2019-08-07 10:32
Hey @piotrek94 

Thanks a lot, I have aplied ypur patch and the connector works again!!!!

Greta job!

**Comment by miguelangelmestres** [comment] 2019-08-07 10:36
@esdrasdemorais  

I followed this guide

I created my own Script on https://script.google.com

I copied the code from the repository and published my own connector.

**Comment by asirota** [comment] 2019-08-07 13:48
> Hey @miguelangelmestres ,
> I experienced the same problem as you. I found where the problem is and I wrote a patch ([MR](https://github.com/googledatastudio/community-connectors/pull/255)). The problem is caused by the order in `schema` in `Response` object for method `getData()`.
> 
> Also, I noticed that `fetch-csv connector` disappeared from the list of possible connectors to choose when I am creating new Data Source. And I am wondering why.
> 
> ![fetch](https://user-images.githubusercontent.com/9871431/62613087-0f0f0e80-b909-11e9-835f-216338578cd8.jpg)

I think the many open source connectors are not well tested or supported so instead of offering them for wider use as part of the connector library, Google is driving them to this repo to install manually and get support directly from this repo. Basically they aren't partner supported so probably only well supported Community connectors will be displayed there in the future. Just a guess.

**Comment by kmotrebski** [comment] 2019-08-07 21:37
I can confirm, I've experienced the same problem and patch from @piotrek94 works! :+1:

**Comment by esdrasdemorais** [comment] 2019-08-12 00:55
> @esdrasdemorais
> 
> I followed this guide https://developers.google.com/datastudio/connector/get-started
> 
> I created my own Script on https://script.google.com
> 
> I copied the code from the repository and published my own connector.

Please @miguelangelmestres, Help me. Yet persist the same error with this code:

**Community Connector Error**

There was an error caused by the community connector. Please report the issue to the provider of this community connector if this issue persists.
Connector details

**There was an error caused by this connector.**

**Comment by miguelangelmestres** [comment] 2019-08-12 11:49
@esdrasdemorais

It seems you are on the right way.

Now test with a very simple CSV with few lines and columns to be sure you are not having a data problem

Make sure that your code is updates with the patch from @piotrek94 
https://github.com/googledatastudio/community-connectors/blob/c82365fe8a46d0eed1f161f8debe0ce922783109/fetch-csv/src/main.js

And finally deploy from manifest and select New in the dropdown
![image](https://user-images.githubusercontent.com/33750346/62862966-c17b1300-bd07-11e9-8713-f791dc0eed7b.png)

Finally get the deployment id to paste it in the comunity connectors field.

Hope this helps

**Comment by diminishedprime** [comment] 2019-08-12 21:59
Just added a comment to #255 that explains why this issue was happening. Thanks for helping each other out! Closing this issue since the original issue has been resolved.

**Closed by diminishedprime** 2019-08-12 21:59 UTC
